### ISSUE TITLE
Extract to concept:Test cases

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge#508]
**Should be able to extract to a new file**
- [x] Select one/more steps to a new concept file
- [x] Select one/more steps to an existing concept file
- [x] Able to extract with simple parameters to concept
- [ ] Should be able to extract with [data from template](https://github.com/getgauge/Intellij-Plugin/issues/194) - before all scenarios
- [x] Able to extract with inline table parameters to concept
- [x] Able to extract with special table parameters i.e csv
- [x] Able to extract from other concepts
- [x] While extracting if concept name has any static parameters it gets converted to dynamic parameter.
- [x] Should not be able to extract if there is an invalid element in the section (eg:- spec headings, scenario headings, tags)
- [x] Should not extract if there is a parse error.
- [x] Incomplete extraction, if file [extension not specified](https://github.com/getgauge/Intellij-Plugin/issues/191)
- [x] Incomplete extraction, if [path does not exist](https://github.com/getgauge/Intellij-Plugin/issues/195)
- [ ] Should not remove any scenario headings while extracting to concept - happens intermittently.

**Should not be able to extract to a spec file or other file types**
- [x] Should not be able to extract to a spec or [other file types](https://github.com/getgauge/Intellij-Plugin/issues/192).

**Should be able to extract to concept from other concepts**

**Validations**
- [x] Should check if this extraction will give raise to [duplicate concept definitions](https://github.com/getgauge/Intellij-Plugin/issues/193)

**Comment by kashishm** [comment]
This feature is released in the [IntelliJ plugin](https://plugins.jetbrains.com/plugin/7535) version [0.2.4](https://github.com/getgauge/Intellij-Plugin/releases/tag/v0.2.4). The documentation for this feature can be found [here](http://getgauge.io/documentation/user/current/ide_support/features.html#extract-concept)
