### ISSUE TITLE
Improve Gauge installation

### ISSUE THREAD

**Issue by sriv** [getgauge/gauge#577]
This is a meta issue, track the issues below for details.

- [x] #544 - Use `GAUGE_ROOT` to customize the location of gauge configs and plugins
- [x] getgauge/gauge-tests#15 - Improve installation on linux (related to above)
- [x] #574 - Include options to install plugins via installer - Windows
- [x] #575 - Include options to install plugins via installer - osx pkg
- [x] #576 - Include options to install plugins via installer - linux

**Comment by sguptatw** [comment]
Test case gauge -v on linux
