### ISSUE TITLE
LSP support for gauge

### ISSUE THREAD

**Issue by nehashri** [getgauge/gauge#717]
Gauge should support [Language Server Protocol (LSP)](https://github.com/Microsoft/language-server-protocol). This brings Gauge IDE support for a broader range of IDE clients supporting LSP like VS-Code.

Gauge LSP should be supported for .spec and .cpt files. In a gauge document, the following features should be available - 

**Code completion**
User can get a list of suggestions. 
1. Suggestions while **authoring a step** should contain 
- [x] concepts and steps with place holders - #718
- [x] unused steps which have an implementation - #753 
- [ ] steps implemented in a different library/module referred in the project

2. Suggestions while **authoring a parameter** should contain 
- [x] static and dynamic parameter suggestions  #762  

3. Suggestions while **authoring a tag** should contain 
- [x] all the tags in the current project https://github.com/getgauge/gauge/issues/824

**[Document Highlights](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#document-highlights-request)** 
- [ ] highlight the dynamic parameter usages. https://github.com/getgauge/gauge/issues/825

**Signature Help:** 
- [ ] Show the annotation text on the step

**Goto Definition:** 
- [x] navigate to implementation support for a step - https://github.com/getgauge/gauge/issues/761
- [x] navigate to the concept selected - https://github.com/getgauge/gauge/issues/760

**Document Links:** compute and resolve links inside a document.
- [ ] navigate to the parameter - file/table selected

**Find References:** 
- [x] step
- [x] concept
- [ ] tag
- [ ] table:csv

**Diagnostics**
- [x] show Diagnostics - parse error,validation error  #823 

**Code Actions:** 
- [x] extract to concept
- [x] implement a step

**Document Formatting:** 
- [x] Specification -  #813 
- [ ] Concept - #817

**Rename/Refactor**: 
- [x] project-wide rename of a step text
- [x] rename a concept heading
- [x] add a parameter to a step
- [x] remove a parameter from a step
- [x] change the position of parameters in a step

**Templates**
On creating a file, the basic template should be in place
- [x] Template for a specification
- [x] Template for a concept

**Test Execution** - [execute a command](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#execute-a-command)
- [ ] folder
- [ ] work-space
- [ ] tag
- [x] re-run failed tests https://github.com/getgauge/gauge-vscode/issues/20

**CodeLens:** 
- [x] debug a scenario/specification
- [x] execute a specification - #830
- [x] execute a scenario - #831
- [ ] execute scenarios for every table row sequential/parallel - #832
- [ ] execute scenario for a given table row https://github.com/getgauge/gauge-vscode/issues/21

**[Telemetry support](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#telemetry_event)**
